### ISSUE TITLE
TemporaryView constructor ignores column names

### ISSUE THREAD

**Issue by adn4n** [lwhite1/tablesaw#84]
The second constructor of TemporaryView class ignores the `String[] columnNames` parameter.

**Comment by adn4n** [comment]
I think having another constructor to create TemporaryView from another TemporaryView would also be super useful. Something along the lines of: 
```
public TemporaryView(TemporaryView tempView, Selection rowSelection, String name) {
	this.name = name;
	this.rowMap = rowSelection;
	rowMap.and(tempView.getRowMap());
	this.table = tempView.getTable();
}
```

**Comment by lwhite1** [comment]
i removed the constructor with columnNames, as it is a duplicate once the unused argument was removed. The fix is on master currently.

Not sure about the new constructor you suggest, although it looks like maybe what you want is an intersection operation between two views.  This is kind of interesting, and suggests that union, set difference, and complement operations might be useful as well. 

would one of these two variations work:

```
public static TemporaryView intersect(TemporaryView one, TemporaryView two) {
    TemporaryView view = new TemporaryView(one.table, one.rowMap );
     view.rowMap.and(two.rowMap);
     return view;
}

```
or (instance method): 

public TemporaryView intersect(TemporaryView other) {
    TemporaryView view = new TemporaryView(this.table, this.rowMap);
     view.rowMap.and(other.rowMap);
     return view;
}

**Comment by lwhite1** [comment]
Closing this issue, but open to more discussion on the question

**Comment by adn4n** [comment]
Removing the constructor with columnNames surely closes the issue. However, I am still wondering if it is possible to create a temporary view of only the selected columns of a table (e.g., temporary view of the first 3 columns of a 5 column table)?
